/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness + database status
         * @description Always returns 200. Read `status` / `database.reachable` for the verdict.
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library listing */
        get: operations["list_documents_v1_documents_get"];
        put?: never;
        /** Import a file or a URL */
        post: operations["import_document_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document + its jobs */
        get: operations["get_document_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_document_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{document_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chunk inspector */
        get: operations["list_chunks_v1_documents__document_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{document_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-parse and re-chunk from the managed copy / origin URL */
        post: operations["reprocess_document_v1_documents__document_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All subjects with document counts */
        get: operations["list_subjects_v1_subjects_get"];
        put?: never;
        /** Create a subject */
        post: operations["create_subject_v1_subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subject */
        get: operations["get_subject_v1_subjects__subject_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job status */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search knowledge: the contents of chunks, by meaning and/or keywords */
        get: operations["search_chunks_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/embeddings/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index coverage */
        get: operations["embedding_status_v1_embeddings_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/embeddings/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue embedding jobs for documents that still need them (resumable) */
        post: operations["index_embeddings_v1_embeddings_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer a question from your library, with citations */
        post: operations["ask_v1_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ask/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The same answer, streamed as server-sent events */
        post: operations["ask_stream_v1_ask_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/llm/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Is the language model ready?
         * @description Always 200 — it describes an unavailable runtime rather than failing like one.
         */
        get: operations["llm_status_v1_llm_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /**
             * Mode
             * @description Retrieval mode; defaults to RAG_MODE
             */
            mode?: ("hybrid" | "semantic" | "keyword") | null;
            /** Top K */
            top_k?: number | null;
            /** Subject Id */
            subject_id?: string | null;
            /** Week */
            week?: number | null;
            /** Kind */
            kind?: ("pdf" | "markdown" | "text" | "docx" | "web" | "youtube") | null;
            /** Document Id */
            document_id?: string | null;
            /** Temperature */
            temperature?: number | null;
            /** Max Tokens */
            max_tokens?: number | null;
        };
        /** AskResponse */
        AskResponse: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /**
             * Refused
             * @description The library had too little evidence; no answer was generated
             */
            refused: boolean;
            /**
             * Grounded
             * @description The answer carries at least one valid citation
             */
            grounded: boolean;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
            /** Sources */
            sources: components["schemas"]["SourceOut"][];
            retrieval: components["schemas"]["RetrievalInfo"];
            generation: components["schemas"]["GenerationInfo"];
        };
        /** Body_import_document_v1_documents_post */
        Body_import_document_v1_documents_post: {
            /**
             * File
             * @description PDF, Markdown, text or DOCX
             */
            file?: string | null;
            /**
             * Url
             * @description Web page or YouTube video URL
             */
            url?: string | null;
            /**
             * Subjects
             * @description Subject names; repeat or comma-separate
             */
            subjects?: string[] | null;
            /** Week */
            week?: number | null;
            /** Title */
            title?: string | null;
        };
        /** ChunkListOut */
        ChunkListOut: {
            /** Items */
            items: components["schemas"]["ChunkOut"][];
            /** Total */
            total: number;
        };
        /** ChunkOut */
        ChunkOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ordinal */
            ordinal: number;
            /** Parent Id */
            parent_id?: string | null;
            /** Heading Path */
            heading_path: string[];
            /** Page Start */
            page_start?: number | null;
            /** Page End */
            page_end?: number | null;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Token Count */
            token_count: number;
            /** Text */
            text: string;
        };
        /**
         * CitationOut
         * @description A marker the model used that resolved to a real retrieved chunk.
         */
        CitationOut: {
            /** Marker */
            marker: number;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Title */
            document_title: string;
            /** Heading Path */
            heading_path: string[];
            /** Page Start */
            page_start?: number | null;
            /** Page End */
            page_end?: number | null;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Text */
            text: string;
        };
        /** DatabaseHealth */
        DatabaseHealth: {
            /** Reachable */
            reachable: boolean;
            /** Server Version */
            server_version?: string | null;
            /** Pgvector Version */
            pgvector_version?: string | null;
            /** Migration Revision */
            migration_revision?: string | null;
            /** Error */
            error?: string | null;
        };
        /** DocumentDetailOut */
        DocumentDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pdf" | "markdown" | "text" | "docx" | "web" | "youtube";
            /** Title */
            title: string;
            /** Origin Uri */
            origin_uri?: string | null;
            /** Storage Path */
            storage_path?: string | null;
            /** Content Hash */
            content_hash: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "ready" | "failed";
            /** Error */
            error?: string | null;
            /** Week */
            week?: number | null;
            /** Classified By */
            classified_by: string;
            /** Subjects */
            subjects: components["schemas"]["SubjectOut"][];
            /** Chunk Count */
            chunk_count: number;
            /**
             * Embedded Chunk Count
             * @description Retrieval chunks with a vector for the configured embedding model
             * @default 0
             */
            embedded_chunk_count: number;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Jobs */
            jobs: components["schemas"]["JobOut"][];
        };
        /** DocumentListOut */
        DocumentListOut: {
            /** Items */
            items: components["schemas"]["DocumentOut"][];
            /** Total */
            total: number;
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pdf" | "markdown" | "text" | "docx" | "web" | "youtube";
            /** Title */
            title: string;
            /** Origin Uri */
            origin_uri?: string | null;
            /** Storage Path */
            storage_path?: string | null;
            /** Content Hash */
            content_hash: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "ready" | "failed";
            /** Error */
            error?: string | null;
            /** Week */
            week?: number | null;
            /** Classified By */
            classified_by: string;
            /** Subjects */
            subjects: components["schemas"]["SubjectOut"][];
            /** Chunk Count */
            chunk_count: number;
            /**
             * Embedded Chunk Count
             * @description Retrieval chunks with a vector for the configured embedding model
             * @default 0
             */
            embedded_chunk_count: number;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EmbeddingStatusOut */
        EmbeddingStatusOut: {
            /** Enabled */
            enabled: boolean;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Dimension */
            dimension: number;
            /** Chunks Total */
            chunks_total: number;
            /** Chunks Embedded */
            chunks_embedded: number;
            /** Documents Total */
            documents_total: number;
            /** Documents Complete */
            documents_complete: number;
            /** Jobs Queued */
            jobs_queued: number;
            /** Jobs Running */
            jobs_running: number;
            /** Jobs Failed */
            jobs_failed: number;
        };
        /** GenerationInfo */
        GenerationInfo: {
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthReport */
        HealthReport: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** App */
            app: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            database: components["schemas"]["DatabaseHealth"];
        };
        /** ImportResponse */
        ImportResponse: {
            document: components["schemas"]["DocumentOut"];
            job?: components["schemas"]["JobOut"] | null;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
        };
        /** IndexRequest */
        IndexRequest: {
            /**
             * Force
             * @description Regenerate even where vectors exist
             * @default false
             */
            force: boolean;
        };
        /** IndexResponse */
        IndexResponse: {
            /** Enqueued */
            enqueued: number;
            /**
             * Skipped
             * @description Documents that already had a job waiting
             */
            skipped: number;
            /** Model */
            model: string;
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /** Last Error */
            last_error?: string | null;
            /**
             * Run After
             * Format: date-time
             */
            run_after: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /** LLMStatusOut */
        LLMStatusOut: {
            /** Enabled */
            enabled: boolean;
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /**
             * Reachable
             * @default false
             */
            reachable: boolean;
            /**
             * Model Available
             * @default false
             */
            model_available: boolean;
            /**
             * Context Window
             * @default 0
             */
            context_window: number;
            /**
             * Max Output Tokens
             * @default 0
             */
            max_output_tokens: number;
            /** Detail */
            detail?: string | null;
        };
        /** RetrievalInfo */
        RetrievalInfo: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "hybrid" | "semantic" | "keyword";
            /** Embedding Model */
            embedding_model?: string | null;
            /**
             * Hits
             * @description Chunks returned by Phase 2 retrieval
             */
            hits: number;
            /**
             * Above Floor
             * @description …of those, the ones that cleared the relevance floor
             */
            above_floor: number;
            /** Min Similarity */
            min_similarity: number;
            /** Top K */
            top_k: number;
            /** Context Tokens */
            context_tokens: number;
        };
        /** SearchHitOut */
        SearchHitOut: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Title */
            document_title: string;
            /** Document Kind */
            document_kind: string;
            /** Origin Uri */
            origin_uri?: string | null;
            /** Subjects */
            subjects: string[];
            /** Week */
            week?: number | null;
            /** Heading Path */
            heading_path: string[];
            /** Page Start */
            page_start?: number | null;
            /** Page End */
            page_end?: number | null;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Ordinal */
            ordinal: number;
            /** Text */
            text: string;
            /**
             * Score
             * @description Ranking score: RRF for hybrid, cosine for semantic, ts_rank for keyword
             */
            score: number;
            /**
             * Similarity
             * @description Cosine similarity (semantic/hybrid)
             */
            similarity?: number | null;
            /**
             * Keyword Score
             * @description ts_rank_cd (keyword/hybrid)
             */
            keyword_score?: number | null;
            /** Semantic Rank */
            semantic_rank?: number | null;
            /** Keyword Rank */
            keyword_rank?: number | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "hybrid" | "semantic" | "keyword";
            /**
             * Model
             * @description Embedding model used for the semantic side
             */
            model?: string | null;
            /** Semantic Candidates */
            semantic_candidates: number;
            /** Keyword Candidates */
            keyword_candidates: number;
            /** Results */
            results: components["schemas"]["SearchHitOut"][];
        };
        /**
         * SourceOut
         * @description A numbered block of context, and where it came from.
         */
        SourceOut: {
            /**
             * Marker
             * @description The [S<marker>] the answer may cite
             */
            marker: number;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Title */
            document_title: string;
            /** Document Kind */
            document_kind: string;
            /** Origin Uri */
            origin_uri?: string | null;
            /** Subjects */
            subjects: string[];
            /** Week */
            week?: number | null;
            /** Heading Path */
            heading_path: string[];
            /** Page Start */
            page_start?: number | null;
            /** Page End */
            page_end?: number | null;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Ordinal */
            ordinal: number;
            /**
             * Text
             * @description Exactly the text the model was shown for this source
             */
            text: string;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /** Score */
            score: number;
            /** Similarity */
            similarity?: number | null;
            /** Semantic Rank */
            semantic_rank?: number | null;
            /** Keyword Rank */
            keyword_rank?: number | null;
        };
        /** SubjectCreate */
        SubjectCreate: {
            /** Name */
            name: string;
            /** Code */
            code?: string | null;
        };
        /** SubjectOut */
        SubjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code?: string | null;
            /** Document Count */
            document_count?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
        };
    };
    list_documents_v1_documents_get: {
        parameters: {
            query?: {
                /** @description Title / filename lookup (case-insensitive) */
                q?: string | null;
                subject_id?: string | null;
                week?: number | null;
                status?: ("pending" | "processing" | "ready" | "failed") | null;
                kind?: ("pdf" | "markdown" | "text" | "docx" | "web" | "youtube") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_document_v1_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_document_v1_documents_post"];
            };
        };
        responses: {
            /** @description Already imported — the existing document is returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chunks_v1_documents__document_id__chunks_get: {
        parameters: {
            query?: {
                level?: "all" | "sections" | "retrieval";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_document_v1_documents__document_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subjects_v1_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOut"][];
                };
            };
        };
    };
    create_subject_v1_subjects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subject_v1_subjects__subject_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_chunks_v1_search_get: {
        parameters: {
            query: {
                /** @description Natural-language query */
                q: string;
                mode?: "hybrid" | "semantic" | "keyword";
                limit?: number;
                subject_id?: string | null;
                week?: number | null;
                kind?: ("pdf" | "markdown" | "text" | "docx" | "web" | "youtube") | null;
                document_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    embedding_status_v1_embeddings_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbeddingStatusOut"];
                };
            };
        };
    };
    index_embeddings_v1_embeddings_index_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["IndexRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_v1_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_stream_v1_ask_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description `sources`, then `delta` events, then `result` (or `error`) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_status_v1_llm_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LLMStatusOut"];
                };
            };
        };
    };
}
