/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness + database status
         * @description Always returns 200. Read `status` / `database.reachable` for the verdict.
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library listing */
        get: operations["list_documents_v1_documents_get"];
        put?: never;
        /** Import a file or a URL */
        post: operations["import_document_v1_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document + its jobs */
        get: operations["get_document_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_document_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{document_id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chunk inspector */
        get: operations["list_chunks_v1_documents__document_id__chunks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{document_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-parse and re-chunk from the managed copy / origin URL */
        post: operations["reprocess_document_v1_documents__document_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All subjects with document counts */
        get: operations["list_subjects_v1_subjects_get"];
        put?: never;
        /** Create a subject */
        post: operations["create_subject_v1_subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subject */
        get: operations["get_subject_v1_subjects__subject_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job status */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_document_v1_documents_post */
        Body_import_document_v1_documents_post: {
            /**
             * File
             * @description PDF, Markdown, text or DOCX
             */
            file?: string | null;
            /**
             * Url
             * @description Web page or YouTube video URL
             */
            url?: string | null;
            /**
             * Subjects
             * @description Subject names; repeat or comma-separate
             */
            subjects?: string[] | null;
            /** Week */
            week?: number | null;
            /** Title */
            title?: string | null;
        };
        /** ChunkListOut */
        ChunkListOut: {
            /** Items */
            items: components["schemas"]["ChunkOut"][];
            /** Total */
            total: number;
        };
        /** ChunkOut */
        ChunkOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ordinal */
            ordinal: number;
            /** Parent Id */
            parent_id?: string | null;
            /** Heading Path */
            heading_path: string[];
            /** Page Start */
            page_start?: number | null;
            /** Page End */
            page_end?: number | null;
            /** Char Start */
            char_start: number;
            /** Char End */
            char_end: number;
            /** Token Count */
            token_count: number;
            /** Text */
            text: string;
        };
        /** DatabaseHealth */
        DatabaseHealth: {
            /** Reachable */
            reachable: boolean;
            /** Server Version */
            server_version?: string | null;
            /** Pgvector Version */
            pgvector_version?: string | null;
            /** Migration Revision */
            migration_revision?: string | null;
            /** Error */
            error?: string | null;
        };
        /** DocumentDetailOut */
        DocumentDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pdf" | "markdown" | "text" | "docx" | "web" | "youtube";
            /** Title */
            title: string;
            /** Origin Uri */
            origin_uri?: string | null;
            /** Storage Path */
            storage_path?: string | null;
            /** Content Hash */
            content_hash: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "ready" | "failed";
            /** Error */
            error?: string | null;
            /** Week */
            week?: number | null;
            /** Classified By */
            classified_by: string;
            /** Subjects */
            subjects: components["schemas"]["SubjectOut"][];
            /** Chunk Count */
            chunk_count: number;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Jobs */
            jobs: components["schemas"]["JobOut"][];
        };
        /** DocumentListOut */
        DocumentListOut: {
            /** Items */
            items: components["schemas"]["DocumentOut"][];
            /** Total */
            total: number;
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pdf" | "markdown" | "text" | "docx" | "web" | "youtube";
            /** Title */
            title: string;
            /** Origin Uri */
            origin_uri?: string | null;
            /** Storage Path */
            storage_path?: string | null;
            /** Content Hash */
            content_hash: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "processing" | "ready" | "failed";
            /** Error */
            error?: string | null;
            /** Week */
            week?: number | null;
            /** Classified By */
            classified_by: string;
            /** Subjects */
            subjects: components["schemas"]["SubjectOut"][];
            /** Chunk Count */
            chunk_count: number;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthReport */
        HealthReport: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** App */
            app: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            database: components["schemas"]["DatabaseHealth"];
        };
        /** ImportResponse */
        ImportResponse: {
            document: components["schemas"]["DocumentOut"];
            job?: components["schemas"]["JobOut"] | null;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /** Last Error */
            last_error?: string | null;
            /**
             * Run After
             * Format: date-time
             */
            run_after: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at?: string | null;
        };
        /** SubjectCreate */
        SubjectCreate: {
            /** Name */
            name: string;
            /** Code */
            code?: string | null;
        };
        /** SubjectOut */
        SubjectOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Code */
            code?: string | null;
            /** Document Count */
            document_count?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
        };
    };
    list_documents_v1_documents_get: {
        parameters: {
            query?: {
                /** @description Title / filename lookup (case-insensitive) */
                q?: string | null;
                subject_id?: string | null;
                week?: number | null;
                status?: ("pending" | "processing" | "ready" | "failed") | null;
                kind?: ("pdf" | "markdown" | "text" | "docx" | "web" | "youtube") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_document_v1_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_document_v1_documents_post"];
            };
        };
        responses: {
            /** @description Already imported — the existing document is returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chunks_v1_documents__document_id__chunks_get: {
        parameters: {
            query?: {
                level?: "all" | "sections" | "retrieval";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_document_v1_documents__document_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subjects_v1_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOut"][];
                };
            };
        };
    };
    create_subject_v1_subjects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subject_v1_subjects__subject_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
